SELECT *
    FROM "STOCKS"
    WHERE VOLUME = (select max(volume) from stocks);

SELECT SYMBOL, SUM(VOLUME) AS VOLUME_ON_DAY FROM "STOCKS"
    WHERE DATE LIKE '%2014-02-24%'
    GROUP BY SYMBOL
    ORDER BY VOLUME_ON_DAY DESC LIMIT 2;