USE ROLE TRAINING_ROLE;
CREATE WAREHOUSE IF NOT EXISTS BEETLE_WH;
USE SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL;

--> after all;

ALTER WAREHOUSE BEETLE_WH SUSPEND;
ALTER WAREHOUSE BEETLE_WH SET WAREHOUSE_SIZE = XSmall;