ALTER WAREHOUSE BEETLE_WH
SET WAREHOUSE_SIZE = XSmall;

ALTER WAREHOUSE BEETLE_WH SUSPEND;
ALTER WAREHOUSE BEETLE_WH RESUME;
ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER SESSION SET QUERY_TAG = 'BEETLE_WH_Sizing';


--> Execute first query;

ALTER WAREHOUSE BEETLE_WH SUSPEND;
ALTER WAREHOUSE BEETLE_WH SET WAREHOUSE_SIZE = Medium;
ALTER WAREHOUSE BEETLE_WH RESUME;

--> Execute second query;

ALTER WAREHOUSE BEETLE_WH SUSPEND;
ALTER WAREHOUSE BEETLE_WH SET WAREHOUSE_SIZE = Large;
ALTER WAREHOUSE BEETLE_WH RESUME;

--> Execute third query;

ALTER WAREHOUSE BEETLE_WH SUSPEND;
ALTER WAREHOUSE BEETLE_WH SET WAREHOUSE_SIZE = XLarge;
ALTER WAREHOUSE BEETLE_WH RESUME;