CREATE OR REPLACE TABLE "BEETLE_WORKSHOPS"."BEETLE_WORKSHOPS_SCHEMA"."WORKSHOP_2"(
    SYMBOL VARCHAR(5),
    DATE TIMESTAMP_LTZ,
    OPEN_STOCK FLOAT,
    HIGH_STOCK FLOAT,
    LOW_STOCK FLOAT,
    CLOSE_STOCK FLOAT,
    VOLUME NUMBER(38,0)
    COMMENT 'This is Miguel Estrada Workshop number 2'
);

#After loading the file;
# Used the past file format;

CREATE TABLE "BEETLE_WORKSHOPS"."BEETLE_WORKSHOPS_SCHEMA"."WORKSHOP_2_ANALYSIS"
    AS SELECT SYMBOL, 
    DATE, dayname(DATE) AS DAY, 
    OPEN_STOCK, LOW_STOCK, 
    HIGH_STOCK, CLOSE_STOCK, 
    VOLUME 
    FROM "BEETLE_WORKSHOPS"."BEETLE_WORKSHOPS_SCHEMA"."WORKSHOP_2";

