USE ROLE TRAINING_ROLE;
CREATE DATABASE IF NOT EXISTS BEETLE_DB;
CREATE WAREHOUSE IF NOT EXISTS BEETLE_WH;
USE WAREHOUSE BEETLE_WH;
ALTER WAREHOUSE BEETLE_WH SET WAREHOUSE_SIZE = xsmall;
USE DATABASE BEETLE_DB;
CREATE SCHEMA IF NOT EXISTS BEETLE_TASKS_SCHEMA;
USE SCHEMA BEETLE_TASKS_SCHEMA;