# Grants
;
GRANT OWNERSHIP ON BEETLE_DB.PUBLIC.BEETLE_TBL TO ROLE TRAINING_ROLE;
GRANT ownership on all tables in schema BEETLE_DB.PUBLIC to role TRAINING_ROLE copy current grants;
GRANT OWNERSHIP ON BEETLE_DB.PUBLIC TO ROLE TRAINING_ROLE;

# Warehouses
;
#Create second warehouse
CREATE WAREHOUSE BEETLE_WH2 WITH
WAREHOUSE_SIZE = XSMALL
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Another warehouse for completing labs';

#Drop warehouse
;
DROP WAREHOUSE BEETLE_WH2;


#Show warehouses
;
SHOW WAREHOUSES LIKE 'BEETLE%';

#Alter warehouse
ALTER WAREHOUSE BEETLE_WH SET WAREHOUSE_SIZE=XSmall;
ALTER WAREHOUSE BEETLE_WH SUSPEND;

ALTER WAREHOUSE BEETLE_WH2 SET
WAREHOUSE_SIZE = Small
AUTO_SUSPEND = 600
MAX_CLUSTER_COUNT = 3;

# Selects
;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA."TPCH_SF1".NATION LIMIT 10;