#Confirming information...
;
SHOW SCHEMAS;

#Executing...
;
USE ROLE TRAINING_ROLE;
USE WAREHOUSE BEETLE_WH;
USE DATABASE BEETLE_DB;
USE ROLE SYSADMIN;
GRANT OWNERSHIP ON SCHEMA BEETLE_DB.PUBLIC TO ROLE TRAINING_ROLE;
USE ROLE TRAINING_ROLE;
USE SCHEMA BEETLE_DB.PUBLIC;