#---
#Creating Database

CREATE DATABASE BEETLE_DB;

#---
# Create Table

CREATE OR REPLACE TABLE BEETLE_DB.PUBLIC.BEETLE_TBL(
    id NUMBER(38,0), 
    name STRING(10),
    country VARCHAR(20), 
    order_date DATE
);

#---
# Dropping and undropping

# If you do a CREATE AND REPLACE with the same 

DROP DATABASE BEETLE_DB;
DROP TABLE BEETLE_TBL;
DROP WAREHOUSE "BEETLE_WH";

UNDROP DATABASE BEETLE_DB;
UNDROP TABLE BEETLE_TBL;
UNDROP WAREHOUSE "BEETLE_WH";

#---
# Create Warehouse

ALTER WAREHOUSE "BEETLE_WH" SET WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD' COMMENT = 'Lab 1 Warehouse creation';

#---
#Generate defaults for specific user

USE ROLE SECURITYADMIN;
ALTER USER miguel_estrada_sbx
SET
DEFAULT_ROLE=TRAINING_ROLE
DEFAULT_NAMESPACE=BEETLE_DB.PUBLIC
DEFAULT_WAREHOUSE=BEETLE_WH;

#---
# Suspend Warehouse
ALTER WAREHOUSE BEETLE_WH SUSPEND;