#Create place in which to save Information
;

CREATE DATABASE BEETLE_WORKSHOPS;
CREATE SCHEMA BEETLE_WORKSHOPS.BEETLE_WORKSHOPS_SCHEMA;
CREATE OR REPLACE TABLE "BEETLE_WORKSHOPS"."BEETLE_WORKSHOPS_SCHEMA"."WORKSHOP_1"(
ID NUMBER(38,0),
PROFIT NUMBER(38,0),
ONLINEBANKING NUMBER(38,0),
AGE VARCHAR(40),
INC VARCHAR(70),
TERNURE FLOAT,
DISTRICT NUMBER(4,0),
COMMENT 'This is Miguel Estrada Workshop number 1'
);

#Defining context
USE DATABASE "BEETLE_WORKSHOPS";
USE SCHEMA "BEETLE_WORKSHOPS_SCHEMA";

#Granting access to all
;

GRANT SELECT ON all tables IN schema "BEETLE_WORKSHOPS"."BEETLE_WORKSHOPS_SCHEMA" TO ROLE PUBLIC;

#Schemas
;

CREATE OR REPLACE FILE FORMAT "BEETLE_WORKSHOPS"."BEETLE_WORKSHOPS_SCHEMA".PILGRIM_BANK SET 
    COMPRESSION = 'AUTO' 
    TYPE = 'CSV'
    FIELD_DELIMITER = ',' 
    RECORD_DELIMITER = '\n' 
    SKIP_HEADER = 1 
    FIELD_OPTIONALLY_ENCLOSED_BY = '\042' 
    TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE 
    ESCAPE = 'NONE' 
    ESCAPE_UNENCLOSED_FIELD = '\134' 
    DATE_FORMAT = 'AUTO' 
    TIMESTAMP_FORMAT = 'AUTO' 
    NULL_IF = ('\\N');

ALTER FILE FORMAT Pilgram_Bank SET
  VALIDATE_UTF8 = TRUE;
  