#Creating database;
CREATE DATABASE BEETLE_CLASSIFIED_DB;

#Creating schema;
CREATE SCHEMA BEETLE_CLASSIFIED_DB.READ_ONLY;
CREATE SCHEMA BEETLE_CLASSIFIED_DB.SUPER_PRIVATE;

CREATE OR REPLACE TABLE BEETLE_CLASSIFIED_DB.SUPER_PRIVATE.SUPER_PRIVATE_MESSAGES(
    MESSAGE VARCHAR(40)
)COMMENT = "This is my secret table... sh";

INSERT INTO BEETLE_CLASSIFIED_DB.SUPER_PRIVATE.SUPER_PRIVATE_MESSAGES VALUES('I like chocolate');
INSERT INTO BEETLE_CLASSIFIED_DB.SUPER_PRIVATE.SUPER_PRIVATE_MESSAGES VALUES('I like milk');